#!/bin/bash
#PBS -l walltime=07:30:00
#PBS -l mem=10gb
#PBS -m n
#PBS -N S1SWOTcoloc
echo "Hello ${1}"
#create by A Grouazel on May 2025

hostname
#nouvelle methode
#. /appli/anaconda/latest/etc/profile.d/conda.sh
#module load conda/latest
pybin=/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/l1bAdev/bin/python
pyexe=/home1/datahome/agrouaze/sources/sentinel1/coloc_SWOT/coloc_SWOT_L3_with_S1_CDSE_TOPS.py
inp1=${1}
inp2=${2}
inp3=${3}
echo 'input 1'${1}
ls -alrt $exeo
echo 'exeo '$exeo
echo 'inp1 '$inp1
echo 'inp2 '$inp2
echo 'inp3 '$inp3
$pybin ${pyexe} --day2treat ${inp1} --mode ${inp2} --outputdir ${inp3} 

echo end of python script exe

